from constants import TileDirection

track_one = [
    TileDirection.INITIAL,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.DOWN,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.DOWN,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.DOWN,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,
    TileDirection.RIGHT,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.DOWN,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,
    TileDirection.RIGHT,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
]