from dance_fire_ice.utils.constants import TileDirection

track_ai1 = [
    TileDirection.INITIAL,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.LEFT,
    TileDirection.LEFT,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.LEFT,
    TileDirection.LEFT,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
]

track_ai2 = [
    TileDirection.INITIAL,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.LEFT,
    TileDirection.LEFT,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
]

track_ai3 = [
    TileDirection.INITIAL,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,

    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,

    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,

    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,

    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,

    TileDirection.LEFT,
    TileDirection.LEFT,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
]

track_ai4 = [
    TileDirection.INITIAL,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,

    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,

    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,

    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,

    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,
    TileDirection.DOWN,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
    TileDirection.UP,
]

track_evaluation = [

]

track_one = [
    TileDirection.INITIAL,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,
    TileDirection.RIGHT,
    TileDirection.UP,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.DOWN,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.DOWN,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.DOWN,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,
    TileDirection.RIGHT,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.DOWN,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,
    TileDirection.RIGHT,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,

    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.DOWN,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.UP,

    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
    TileDirection.RIGHT,
]